name: Upload JSON to MongoDB

on:
  push:
    branches:
      - master
    paths:
      - '**.json'  # This will only trigger the workflow when any .json file changes
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache MongoSH
      id: cache-mongosh
      uses: actions/cache@v2
      with:
        path: ~/mongosh
        key: ${{ runner.os }}-mongosh-2

    - name: Setup MongoSH
      if: steps.cache-mongosh.outputs.cache-hit != 'true'
      uses: boly38/action-mongo-tools@v1.0.1
      with:
        mongo-shell: 'true'
        mongo-tools: 'false'

    - name: Find MongoSH path and copy to cache directory
      if: steps.cache-mongosh.outputs.cache-hit != 'true'
      run: |
        which mongosh
        mkdir -p ~/mongosh
        cp $(which mongosh) ~/mongosh/
        
    - name: Use cached MongoSH
      if: steps.cache-mongosh.outputs.cache-hit == 'true'
      run: |
        echo "~/mongosh" >> $GITHUB_PATH

    - name: Clear collection and upload files
      run: |
        echo "Connecting to MongoDB..."
        mongosh "${{ secrets.MONGO_URI }}" --username "${{ secrets.MONGO_USERNAME }}" --password "${{ secrets.MONGO_PASSWORD }}" --eval "
          db.translations.drop();
          print('Collection translations dropped.');
        "
        for file in *.json
        do
          echo "Uploading $file..."
          mongosh "${{ secrets.MONGO_URI }}" --username "${{ secrets.MONGO_USERNAME }}" --password "${{ secrets.MONGO_PASSWORD }}" --eval "
            const fs = require('fs');
            const data = JSON.parse(fs.readFileSync('$file', 'utf8'));
            print('Number of records:', data.length);
            try {
              db.translations.insertMany(data);
              print('$file uploaded.');
            } catch (e) {
              print('Error inserting data:', e.message);
            }
          "
        done
      shell: bash
