name: Import JSON Files to MongoDB

on:
  push:
    branches:
      - master  # Adjust if your main branch has a different name
  workflow_dispatch:  # Allows manual triggering

jobs:
  mongo-import:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Mongo import files
      uses: eamonwoortman/mongo-import-action@0.1
      with:
        path: '*.json'  # Import all JSON files in the root directory
        uri: ${{ secrets.MONGO_URI }}  # Your MongoDB connection string
        database: 'bible'  # Your database name
        collection: 'translations'  # Your collection name
        keep-collection: 'false'  # Keep the existing collection and import new files
        if-no-files-found: 'warn'  # Warn if no files are found, but do not fail the action
