name: Upload JSON to MongoDB

on:
  push:
    branches:
      - master 
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache MongoSH
      id: cache-mongosh
      uses: actions/cache@v2
      with:
        path: /usr/bin/mongosh
        key: ${{ runner.os }}-mongosh-${{ hashFiles('**/lock-files') }}

    - name: Setup MongoSH
      if: steps.cache-mongosh.outputs.cache-hit != 'true'
      uses: boly38/action-mongo-tools@v1.0.1
      with:
        mongo-shell: 'true'
        mongo-tools: 'false'

    - name: Clear collection and upload files
      run: |
        echo "Connecting to MongoDB..."
        mongosh "${{ secrets.MONGO_URI }}" --username "${{ secrets.MONGO_USERNAME }}" --password "${{ secrets.MONGO_PASSWORD }}" --eval "
          use bible;
          db.translations.drop();
          print('Collection translations dropped.');
        "
        for file in *.json
        do
          echo "Uploading $file..."
          mongosh "${{ secrets.MONGO_URI }}" --username "${{ secrets.MONGO_USERNAME }}" --password "${{ secrets.MONGO_PASSWORD }}" --eval "
            use bible;
            const fs = require('fs');
            const data = JSON.parse(fs.readFileSync('$file', 'utf8'));
            db.translations.insertMany(data);
            print('$file uploaded.');
          "
        done
      shell: bash
