name: Update MongoDB Collection with All JSON Files

on:
  push:
    branches:
      - master  # Adjust with the name of your branch
  workflow_dispatch:  # This allows you to manually trigger the action

jobs:
  update-mongodb:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Process JSON files
      run: |
        for jsonfile in *.json; do
          echo "Processing $jsonfile"
          mongoimport --uri ${{ secrets.MONGO_URI }} --db bible --collection translations --file $jsonfile --jsonArray
          echo "$jsonfile has been processed"
        done
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }} # Ensure this secret is set with your MongoDB URI
