name: Rewrite MongoDB Collection

on:
  push:
    branches:
      - main  # Adjust with the name of the branch on which you want to trigger the action
  workflow_dispatch:  # This enables manual triggering

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - id: set-matrix
      run: |
        JSON_FILES=$(ls *.json | jq -R -s -c 'split("\n")[:-1]')
        echo "::set-output name=matrix::${JSON_FILES}"

  rewrite-mongo-collection:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jsonfile: ${{fromJson(needs.prepare.outputs.matrix)}}
    steps:
    - name: Print selected JSON file
      run: echo "Selected JSON file - ${{ matrix.jsonfile }}"

    - name: Mongo Export
      uses: tejasmr/mongoexport@v1
      with:
        uri: ${{ secrets.MONGO_URI }}
        export: ${{ matrix.jsonfile }}
        db: 'bible'
        collection: 'translations'
        rewrite: 'true'
