name: Update MongoDB Collection with KJV

on:
  push:
    branches:
      - master  # Adjust with the name of your branch
  workflow_dispatch:  # This allows you to manually trigger the action

jobs:
  update-mongodb:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print selected JSON file
      run: echo "Updating MongoDB with kjv.json"

    - name: Mongo Export
      uses: tejasmr/mongoexport@v1
      with:
        uri: ${{ secrets.MONGO_URI }} # Ensure this secret is set with your MongoDB URI
        export: 'kjv.json' # Specifying the kjv.json file
        db: 'bible' # Replace with your actual database name
        collection: 'translations' # Replace with your actual collection name
        rewrite: 'true' # This option is to rewrite the data
