name: Rewrite MongoDB Collection

on:
  push:
    branches:
      - master  # Adjust with the name of the branch on which you want to trigger the action
  workflow_dispatch:

jobs:
  rewrite-mongo-collection:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        jsonfile: ${{fromJson(steps.set-matrix.outputs.jsonfiles)}}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up matrix for JSON files
      id: set-matrix
      run: echo "::set-output name=jsonfiles::$(ls *.json | jq -R -s -c 'split("\n")[:-1]')"

    - name: Print selected JSON file
      run: echo "Selected JSON file - ${{ matrix.jsonfile }}"

    - name: Mongo Export
      uses: tejasmr/mongoexport@v1
      with:
        # The URI of the server without username and password
        uri: ${{ secrets.MONGO_URI }}  # Reference to the MongoDB URI stored in GitHub secrets
        # Json file path
        export: ${{ matrix.jsonfile }}  # Dynamic path from matrix
        # Name of the db
        db: 'bible'  # Replace with the name of your database
        # Name of the collection
        collection: 'translations'  # Replace with the name of your collection
        # Should rewrite data
        rewrite: 'true'  # Set to true if you want to rewrite the data
